mysite1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.views.generic import RedirectView


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('', RedirectView.as_view(url='/polls/', permanent=True)),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

from .views import ProductLoginView, ProductLogoutView, ProductLogoutView, profile, RegisterUserView

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', profile, name='profile'),
    path('service/<int:id>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', ProductLoginView.as_view(), name='login'),
    path('logout/', ProductLogoutView.as_view(), name='logout'),
    path('service/', views.all_products, name='service'),
]

polls/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, FileExtensionValidator
from django.db import models
from django.dispatch import Signal
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string


class Order(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)



class Product(models.Model):
    product_name = models.CharField(max_length=200, verbose_name='Название товара/услуги')
    description_product = models.CharField(max_length=3000, verbose_name='Описание')
    pub_date = models.DateTimeField('date published')
    product_img = models.ImageField(verbose_name='Картинка', upload_to='products/', blank=True, null=True,
                            validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])
    user = models.ForeignKey('User', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])

class User(AbstractUser):
    username = models.CharField(max_length=200, verbose_name='Логин', unique=True, blank=False)
    avatar = models.ImageField(upload_to='avatars/', verbose_name='Аватар', blank=False,
                               null=True,
                               validators=[FileExtensionValidator(
                                   allowed_extensions=['png', 'jpg', 'jpeg'])])
    password = models.CharField(max_length=200, verbose_name='Пароль', blank=False)

    USERNAME_FIELD = 'username'

    def __str__(self):
        return str(self.username)


user_registrated = Signal()

polls/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import User, Order
from .models import user_registrated


class RegisterUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput, )
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите тот же самый пароль еще раз')

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=True)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = User
        fields = ('username', 'avatar')


class OrderForm(forms.ModelForm):
    quantity = forms.IntegerField(min_value=1, max_value=100)

    class Meta:
        model = Order
        fields = ['quantity']

polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Count
from django.db.models.functions import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Product, User, Order
from django.urls import reverse
from django.views import generic
from .forms import RegisterUserForm, OrderForm
from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy


def index(request):
    products_requests = Product.objects.order_by('-pub_date')[:5]
    return render(request, 'index.html', {'products_requests': products_requests})


@login_required
def profile(request):
    current_user = request.user
    orders = Order.objects.filter(user=current_user)
    context = {'orders': orders}
    return render(request, 'main/profile.html', context)

class ProductDetailView(generic.DetailView):
    pk_url_kwarg = 'id'
    model = Product
    template_name = 'products/product_detail.html'
    form_class = OrderForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            product = self.get_object()
            order = form.save(commit=False)
            order.user = request.user
            order.product = product
            order.save()
            messages.success(request, 'Товар/услуга успешно заказан!')
            return redirect('polls:profile', id=product.id)
        else:
            messages.error(request, 'Ошибка заказа товара/услуги.')
            return self.get(request, *args, **kwargs)


def all_products(request):
    product_requests = Product.objects.all()
    return render(request, 'products/all_products.html', {'product_requests': product_requests})





class ProductLoginView(LoginView):
    template_name = 'main/login.html'


class ProductLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class RegisterUserView(CreateView):
    model = User
    template_name = 'registration/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('polls:profile')


def search_view(request):
    query = request.GET.get('query')
    results = []

    if query:
        results = Product.objects.filter(title__icontains=query)

    context = {'results': results}
    return render(request, 'products/search_result.html', context)

polls/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='slim' %}
    <title>{% block title %} Главная {% endblock %} </title>
</head>
<body>
<div class="container-fluid">
    <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3  bg-white border-bottom box-shadow">
        <h5 class="mr-md-auto p-2"><a href="{% url 'polls:index' %}">Фирма</a></h5>
        <a class="p-2 text-dark" href="{% url 'polls:service' %}">Товары/услуги</a>

        {% if user.is_authenticated %}

            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Профиль</a>
                <div class="dropdown-menu">
                    <p><a href="{% url 'polls:profile' %}">Профиль</a></p>
                    <form method="post" action="{% url 'polls:logout' %}" class="dropdown-item">
                        {% csrf_token %}
                        <button type="submit">Выйти</button>
                    </form>
                </div>
            </div>
        {% endif %}

        {% if not user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'polls:register' %}">Регистрация</a>
            <a class="p-2 text-dark" href="{% url 'polls:login' %}">Вход</a>
        {% endif %}
    </div>
    <div class="row">

        {% if user.is_authenticated %}


        <nav class="col-md-auto nav flex-column">
            <span class="nav-link root font-weight-bold">
               Пользователь: {{ user.get_username }} <img src="{% thumbnail user.avatar 'default' %}">
           </span>
        </nav>

        {% endif %}

    </div>

    <div class="container">
        {% block content %}
            {% endblock %}
    </div>

    <footer class="mt-3 border-top">

    </footer>
</div>

</body>
</html>

polls/templates/index.html
{% extends "base.html" %}
{% block content %}
{% if products_requests %}
    {% for product in products_requests %}

        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="/media/{{ product.product_img }}" alt="Card image cap">
            <div class="card-body">
                <h5>{{product.product_name}}</h5>
                <p class="card-text">Описание: {{product.description_product}}</p>
            </div>
        </div>

    {% endfor %}
{% else %}
<p>
    Нет товаров/услуг!
</p>
{% endif %}
{% endblock %}

polls/templates/main/login.html
{% extends "base.html" %}
{% block content %}
  {% if form.errors %}
    <p>Ваше имя пользователя и пароль не совпадают. Пожалуйста, попробуйте еще раз.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>У вашего аккаунта нет доступа к этой странице. Продолжать,
      пожалуйста, войдите с учетной записью, которая имеет доступ.</p>
    {% else %}
      <p>Пожалуйста, войдите, чтобы увидеть эту страницу.</p>
    {% endif %}
  {% endif %}

  <form method="post" action="{% url 'polls:login' %}">
    {% csrf_token %}
    <table>
      <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
    </table>
    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>
{% endblock %}

polls/templates/main/logout.html
{% block title %} Выход {% endblock %}


{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

polls/templates/main/profile.html
{% extends "base.html" %}
{% block content %}
<h2>Мои заказы</h2>
{% if orders %}
<ul>
    {% for order in orders %}
    <p>Название: {{ order.product.product_name }}</p>
    <p>Описание: {{ order.product.description_product }}</p>
    <p>Фото: <img class="img" src="/media/{{ order.product.product_img }}"></p>
    {% endfor %}
</ul>
{% else %}
  <p>Нет моих заказов</p>
{% endif %}
{% endblock %}

polls/templates/products/all_products.html
{% extends "base.html" %}

{% block content %}
  <h2>Все товары/услуги</h2>

    <div>
        <form class="form form-search" method="get">
            <input type="search" placeholder="Поиск" name="query">
            <button type="submit">Поиск</button>
        </form>
    </div>

  {% for product in product_requests %}

    <div class="card" style="width: 22rem; margin: 23px;">
        <img src="{{ product.product_img.url }}" alt="{{ product.product_img }}" class="card-img-top">
      {% if products.image_design %}
          <img src="{{ request.image_design.url }}" class="card-img-top">
      {% endif %}
      <div class="card-body">
        <p class="card-text">Название: <a href="{% url 'polls:product_detail' product.id %}">{{ product.product_name }}</a></p>
        <p class="card-text">Описание: {{ product.description_product }}</p>
      </div>
    </div>
  {% empty %}
    <p>Нет доступных товаров/услуг</p>
  {% endfor %}
    </form>

{% endblock %}

polls/templates/products/product_detail.html
{% extends "base.html" %}
{% block title %}<title>Отдельный товар/услуга</title>{% endblock %}
{% block content %}
    <div>
        <form class="form form-search" method="get">
            <input type="search" placeholder="Поиск" name="query">
            <button type="submit">Поиск</button>
        </form>
    </div>
    <div>
        <p>Название: {{product.product_name}}</p>
        <p>Описание: {{product.description_product}}</p>
        <p>Фото: <img class="img" src="/media/{{ product.product_img }}"></p>
    </div>

    <form method="post" action="{% url 'polls:product_detail' product.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Заказать товар/услугу">
    </form>
{% endblock %}

polls/templates/products/product_list.html
{% extends "base.html" %}
{% block content %}
<h2>Мои товары/услуги</h2>
{% if products_requests %}
<ul>
    {% for product in products_requests %}
    <p><a href="{% url 'polls:product' product.id %}">Название: {{ product.product_name }}</a></p>
    <p>Описание: {{ product.description_product }}</p>
    <p>Фото: <img class="img" src="{{ product.product_img.url }}"></p>
    {% endfor %}
</ul>
{% else %}
  <p>Нет моих товаров/услуг</p>
{% endif %}
{% endblock %}

polls/templates/products/results.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:index'%}">Вернуться к вопросам</a>
{% endblock %}

polls/templates/products/search_result.html
{% extends "base.html" %}
{% block content %}
<h2>Мои товары/услуги</h2>
<div>
    <form class="form form-search" method="get">
        <input type="search" placeholder="Поиск" name="query">
        <button type="submit">Поиск</button>
    </form>
</div>
{% if results %}
<ul>
    {% for result in results %}
    <p><a href="{% url 'polls:product' service.id %}">Название: {{ result.product_name }}</a></p>
    <p>Описание: {{ result.description_product }}</p>
    <p>Фото: <img class="img" src="/media/{{ result.product_img }}"></p>
    {% endfor %}
</ul>
{% else %}
  <p>Нет моих товаров/услуг</p>
{% endif %}
{% endblock %}